require:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rake

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Metrics/AbcSize:
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"
    - "Rakefile"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Exclude:
    - "test/**/*"

Minitest/MultipleAssertions:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rake/Desc:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Exclude:
    - "Rakefile"
    - "test/**/*"

Style/DoubleNegation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrivialAccessors:
  AllowPredicates: true
