sudo: false
language: ruby
cache: bundler
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
before_install:
  - gem update --system || echo "Skipping rubygems upgrade"
  - gem install bundler --no-document
