source "https://rubygems.org"
gemspec

gem "amazing_print", "~> 2.0"
gem "irb"
gem "minitest", "~> 6.0"
gem "minitest-mock", "~> 5.27"
gem "minitest-rg", "~> 5.3"
gem "rake", "~> 13.0", "!= 13.0.2"
gem "rexml", "~> 3.2"
gem "rubocop", "1.87.0"
gem "rubocop-minitest", "0.39.1"
gem "rubocop-packaging", "0.6.0"
gem "rubocop-performance", "1.26.1"
gem "rubocop-rake", "0.7.1"
gem "webmock", "~> 3.1"
