source "https://rubygems.org"
gemspec

gem "amazing_print", "~> 1.0"
gem "minitest", "~> 5.0"
gem "minitest-ci", "~> 3.4"
gem "minitest-reporters", "~>1.1"
gem "rake", "~> 13.0", "!= 13.0.2"
gem "rexml", "~> 3.2"
gem "rubocop", "1.16.0"
gem "rubocop-minitest", "0.13.0"
gem "rubocop-packaging", "0.5.1"
gem "rubocop-performance", "1.11.3"
gem "rubocop-rake", "0.6.0"
gem "webmock", "~> 3.1"
